[book]

title = "The Rust Reference"
author = "The Rust Project Developers"

[output.html]
additional-css = ["theme/reference.css"]
git-repository-url = "https://github.com/rust-lang/reference/"

[output.html.redirect]
"/expressions/enum-variant-expr.html" = "struct-expr.html"

[build]
build-dir = "../reference-l10n/book"

[preprocessor.translation]
